print("first name: Sherboto")
print("last name: Jusupov")
print("age: 19 years")
print("sex: male")
print("place of study: International Ala-Too University")
print("course of study: 1 course")
print("faculty: Computer Science")
print("experience in programming: started at University ")
print("desired salary: it depends on my skills")
