#love
marital_status = "single/married "
sex ="female/male"
character_love = "monogamous/not monogamous"
have_children = "1-2, 2-4, 3-6"
friendzone = "yes/no"
character_love1 = "long/short date"
placefirst_date = "restaurant/coffe-bar/lounge-bar/square/park/moll"
sex1 = "virgin/not a virgin"
act ="die/love"

#religion
religion_status = "believer/atheist"
faith = "islam/christian/judaism"
books = "Qoran/Bible/Tora"
believe = "paradise/hell"
myth = "scandinavian/egypt/roman/greek"
theoryofDarwin = "true/false"
placeofpray = "mosque/church/synagogue"
buildings = "kaballah"
wear = "all-close/ordinary"

#space
solar_system = "one/two"
stars = "hot/cold"
ast_abservatory = "telescope"
hugeplace= "NASA"
firstastronaut = "Juriy Gagarin"
firstmoonast = "Nil Armstrong"
firstanimal = "dog"
date = "12 April 1961"
firstspaceship = "Vostok-1"

#car
model = "Mercedes-Benz"
series ="W223" 
manufactured = "Germany"
year = "2021"
distance = "95 milies"
color = "black"
engine = "3.0 biTurbo"
fuel = "gas"
fuel consumption = "10 litres"

#nature
pet = "dog"
animal = "horse"
predator = "shark"
plant = "narciss"
time = "sun"
act = "thunder"
lake = "Issyk-Kul"
ocean = "Indian"
mountain = "Everest"
